[project]
name = "scope"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.13"
dependencies = []

[tool.setuptools.packages.find]
where = ["backend"]
exclude = ["web*", "workers*", "node_modules*"]
