name = "scope-workers"
main = "src/index.ts"
compatibility_date = "2025-12-01"

[observability]
enabled = false
head_sampling_rate = 1

[observability.logs]
enabled = true
head_sampling_rate = 1 # Capture all logs
persist = true # Store logs persistently so you can view them later in the dashboard
invocation_logs = true # Log metadata about each req invocation

[observability.traces]
enabled = false